### ISSUE TITLE
Depth image always the same 

### ISSUE THREAD

**Issue by lisajamhoury** [asornoso/azure-kinect-node-wrapper#1]
I'm trying to get a constant stream from the depth camera onto my canvas in Electron. My first image works great. It appears correctly when I draw it to the canvas. From there, I can't get a second image to load from the Kinect. I'm using setInterval() to call myDevice.getDepthData() every several seconds, but the buffer I receive is always the same as the first image. Is there a way to get the feed of new images, rather than just the one image only?  

```
let depthInterval, depthData

function openKinect() {
    console.log('opening kinect')

    let code = myDevice.openDevice()
    
    if(code != 0 ){
        process.exit()
    } 

    //Configure device
    myDevice.configureDepthMode(1)
    myDevice.configureFPS(15)

    console.log(`Start Cameras Code: ${myDevice.startCameras()}`)
    console.log(`GetFrame Code: ${myDevice.getFrame()}`)
    
} 

function startDepth() {
    console.log('start depth')

    // runs every three seconds 
    depthInterval = setInterval(runDepthFeed, 3000)

}

function runDepthFeed() {
    
    // depth data is the same every time I run setInterval 
    depthData = myDevice.getDepthData()
    
    drawDepthData(depthData)
}

```

**Comment by asornoso** [comment]
Don't forget to get a new frame each interval as well. 

Open camera, configure, in loop(getFrame, getSomeTypeOfData), close camera

**Comment by lisajamhoury** [comment]
That did the trick. Thanks!
