### ISSUE TITLE
Feature: Include Body Tracking SDK

### ISSUE THREAD

**Issue by lisajamhoury** [asornoso/azure-kinect-node-wrapper#2]
Thanks for this excellent wrapper! Do you have any plans to extend the module to include the body tracking SDK?

**Comment by asornoso** [comment]
Eventuality, yes. Possibly as a seperate npm package.

**Comment by lisajamhoury** [comment]
Great. If I have time in the next few weeks I may also start work on this using your wrapper as an example. Will share if I get started.
